### ISSUE TITLE
bug with single image view location

### ISSUE THREAD

**Issue by sahilneal** [m-khvoinitsky/dark-background-light-text-extension#100]
1st i am a huge fan of ur project which save my eyes. i am using this beta addon in firefox beta 57b12 in linux.
after installing it every time when i open any image in new tab on firefox the location of image in browser changed from centre to left side kindly fix it rest is all working fine as like as stable version. see screenshot example
after extension installed single image viewing in firefox is left side which is annoying 
![b4 ext](https://user-images.githubusercontent.com/5617285/32148583-551402ac-bd0a-11e7-8ac6-0ec0e6b12df8.png)
b4 extension installed single image viewing in firefox is centred which is good & default
![screenshot from 2017-10-30 00-33-55](https://user-images.githubusercontent.com/5617285/32148584-558b521c-bd0a-11e7-9198-98d4f133e17c.png)

**Comment by m-khvoinitsky** [comment]
The problem is that [bug 1393022](https://bugzilla.mozilla.org/show_bug.cgi?id=1393022)/#96 workaround tries to load stylesheets from image-only webpage (internally, there is still a webpage) to inject them inline but fails because they're chrome:// and resource:// urls which are restricted for WebExtensions.

**Comment by sahilneal** [comment]
Billion thanks for this bug fix... ur add-on is really awsm. & this bug irritate me a lots even i am thinking to move on ff to chrm...  really ur add on saves my growing eyesight numbers... Thanks again...
