### ISSUE TITLE
Regarding the notes for the WebExtensions update (0.6.0)

### ISSUE THREAD

**Issue by claustromaniac** [m-khvoinitsky/dark-background-light-text-extension#103]
> It isn't possible to process some pages anymore. In particular: all Firefox internal pages (about:preferences, about:addons, about:config, etc), other add-ons internal pages, and addons.mozilla.org. Extension will tell you that "Modification of this page is not available due to Firefox restrictions" in it's pop-up in such cases. We have to live with that.

You might find [this information](https://www.ghacks.net/2017/10/27/how-to-enable-firefox-webextensions-on-mozilla-websites/) useful.

Thank you, by the way. I started using this addon not too long ago and it's really nice.

**Comment by cvcore** [comment]
Is there any other way to darken internal firefox pages, especially new tab and about:preferences.

It's hard to bear the white screen on every new-tab page since the new update.

**Comment by themetricguy** [comment]
Compare to the previous version this one is failing on 50% webpages I've visited since upgrade. These include https://encrypted.google.com/advanced_search and https://addons.mozilla.org/en-GB/firefox/addon/dark-background-light-text/versions/ so, I supposed, it has been release prematurely. Downgraded to previous version.

**Comment by claustromaniac** [comment]
@cvcore  As far as I know, since this limitation is imposed by Firefox itself, we have very few options until Firefox 57 is released. 

We can stick to a legacy version of this add-on for the time being, which requires us to disable add-on automatic updates. Personally, I think I will use a custom new tab while I wait for Firefox 57 to come out. On FF 57 I will ditch the custom new tab and set the new  _privacy.resistFingerprinting.block_mozAddonManager_ preference to lift the restriction for all of my installed extensions, as explained in the article above.

**Comment by cvcore** [comment]
@claustromaniac many thanks for the clarification. Currently switching back to 0.5.14 is a good temporary option for me. But I still hope there will be a way to allow trusted extensions to run in firefox internal webpages, as tweaking hidden preferences may not be so straightforward for ordinary users.

**Comment by m-khvoinitsky** [comment]
@claustromaniac, thank you for the information, I wasn't aware of [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1310082#c24). However:
* It only works for addons.mozilla.org, not for internal Firefox pages.
* I can't set this preference from add-on because it's impossible for WebExensions to do.
* This restriction is a security restriction which was introduced for a reason. I'd recommend avoiding it in your main browser profile. If you need to use addons.mozilla.org a lot for something like leaving reviews, releasing add-ons, etc, you can use separate profile with only my add-on for that with this option set (personally, I'm going to do this way).

**Comment by m-khvoinitsky** [comment]
@themetricguy, https://encrypted.google.com/advanced_search  issues is beyond the scope of current issue. By the way, it works now, seems to be fixed in one of recent bugfix versions.

addons.mozilla.org is impossible to process anymore.

**Comment by m-khvoinitsky** [comment]
@cvcore 
> Is there any other way to darken internal firefox pages, especially new tab and about:preferences. It's hard to bear the white screen on every new-tab page since the new update.

I'm not aware of any.

> Or is it possible for the user to compile the extension sourcecode themselves to lift the restrictions?

It's not extension's restriction, it Firefox' one.

**Comment by m-khvoinitsky** [comment]
Nothing to do here, closing.
