### ISSUE TITLE
52.4.0 (32-bit)

### ISSUE THREAD

**Issue by csxepx** [m-khvoinitsky/dark-background-light-text-extension#106]
52.4.0 (32-bit). Old version, ESR.

colors of links (and/or some others) do not match with setup.
Plz stop gettin' it better. :) That was best tool for XP.
Also now new errors appeared than was been, "on flat road". It's broken maybe? :)

**Comment by m-khvoinitsky** [comment]
> colors of links (and/or some others) do not match with setup.

Fixed in 0bce72538edcf069860e8760b6842ac7084ad2db
Released in [0.6.3](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/?page=1#version-0.6.3).

> Also now new errors appeared than was been, "on flat road". It's broken maybe? :)

Some other issues has been fixed in previous bugfix releases, test now and if anything persists, please, create separate issue.
