### ISSUE TITLE
3 bugs I found on Firefox Quantum

### ISSUE THREAD

**Issue by lonewulfeu** [m-khvoinitsky/dark-background-light-text-extension#123]
First of all thanks for this great plugin.

I noticed 3 issues when using default/invert modes on Firefox Quantum.

1) Images that open in lightbox on websites do not appear on the center of the screen (they get lost)
2) When trying to open chatbox in facebook (not messenger) it makes the page scroll down and the chat window is not visible
3) On some sites youtube embedded video content colors appear "inverted" (can you disable the filter for all videos?)

**Comment by jlanza** [comment]
for 3. in my case most youtube videos doesn't show up. It is just a black square I cannot click. I have to fully disable the extension in order to watch the video (it is not enough with adding the extension to the configured pages)

**Comment by m-khvoinitsky** [comment]
First, make sure that you're using latest add-on version (0.6.6 at the moment).
Always specify which method produces some certain issue. And provide example affected pages, preferably with screenshots.
1. See above
2. I guess it's "Invert". That's not related to Quantum. This is a Firefox bug and it exists since something about Firefox 25 — 30.
3. Provide examples.
> (can you disable the filter for all videos?)

It's not that easy in general case.

**Comment by lonewulfeu** [comment]
1) For the lightbox issue, scroll down to the showcase gallery and click on images with the addon enabled:
http://fancyapps.com/fancybox/3/
This happens with every lightbox element, fancybox is just an example.

2) The facebook chatbox bug only happens when the addon is enabled though. Also when you scroll down on facebook the content they have on each side gets lost (more visible on facebook marketplace).
I think it's a similar issue with 1) when you click on a web element that is supposed to open something, e.g a lightbox or the facebook chatbox it triggers a scroll event for some reason.

**Comment by m-khvoinitsky** [comment]
Both issues caused by #126 (Firefox bug). As I said, it's not related to Quantum, it existed before. All I can recommend is using Stylesheet Processor.

**Comment by jlanza** [comment]
@m-khvoinitsky 

3. Here you have an example [1]. With the extension Enabled I'm not able to see the video, just a blank square. In order to see it, I have to fully disable (unclick Enabled check box), as just only clicking on Disable for a specific website it is not working.

[1]: https://www.windowscentral.com/why-windows-tab-sets-game-changer-productivity

**Comment by lonewulfeu** [comment]
For me I can see the video above but it's inverted. Only with css it looks correct.

**Comment by jlanza** [comment]
Here you can see my result at [1].

![untitled](https://user-images.githubusercontent.com/180640/33549836-2a1471e2-d8ec-11e7-9430-a9fc0538d5db.png)

There is no way to click on it :( What can i do? the only thing is to temporally fully disable the extension.

[1] https://www.espinof.com/trailers/tras-ver-el-primer-teaser-de-jurassic-world-el-reino-caido-necesitamos-un-velociraptor-en-nuestra-vida

**Comment by jlanza** [comment]
The code of the site is like this:
`<div class="article-asset-video article-asset-large">
 <div class="asset-content">
  <div class="base-asset-video">
   <iframe width="1000" height="563" src="//www.youtube.com/embed/5DCg7XVuJKY" frameborder="0" allowfullscreen></iframe>
  </div>
 </div>
</div>`

It seems that it youtube iframes.

**Comment by m-khvoinitsky** [comment]
I've created separate bug for inverted embedded videos #146
