### ISSUE TITLE
Higher CPU usage with a lot of restored (not yet loaded) tabs

### ISSUE THREAD

**Issue by benoit-pierre** [m-khvoinitsky/dark-background-light-text-extension#15]
Steps to reproduce, starting from a pristine new Firefox profile:

* open `about:config` and set the following entries:
```
browser.sessionstore.interval    1500000
browser.newtabpage.enabled    true
browser.startup.page    3
```

* install the extension

* now, starting with only one blank tab, open a bunch (~30) more (lightweight) tabs with `Ctrl+t`, and wait for CPU usage to settle: ~1%

* restart: all the tabs are restored (but only the current tab is loaded), wait for CPU usage to settle: ~15%

* disable the extension through it's control icon: CPU usage settles back to ~1%

* if re-enabled, CPU usage climb back to 15%, but if all the tabs are loaded (e.g. by cycling through them with `Ctr+PageUp`), then the CPU usage lowers back to ~1%

Extension version: 0.5.5
Firefox version: Mozilla/5.0 (X11; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0

**Comment by willsALMANJ** [comment]
I see similar behavior. It  only happens for the stylesheet processor method, not css or invert.

**Comment by benoit-pierre** [comment]
I think the problem is the way the extension poll each tab's document state [with a timeout](https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/master/lib/methods/stylesheet-processor-abstract.js#L143). I think what should be done instead is to use the [`readystatechange`]( https://developer.mozilla.org/en-US/docs/Web/Events/readystatechange) event to monitor changes.

**Comment by benoit-pierre** [comment]
Tentative patch:

```diff
--- a/lib/methods/stylesheet-processor-abstract.js     2016-05-14 18:53:16.330468669 +0200
+++ b/lib/methods/stylesheet-processor-abstract.js        2016-07-24 19:21:35.881363973 +0200
@@ -2,7 +2,6 @@

 var { Class } = require('sdk/core/heritage');
 let { defer } = require('sdk/lang/functional');
-var { setTimeout } = require("sdk/timers");
 // TODO: http://www.ecma-international.org/ecma-262/6.0/ — very slow
 // FIXED: http://www.wsj.com/articles/why-apple-should-kill-off-the-mac-1434321848 — bad colors
 // WORKS: http://www.opennet.ru/opennews/art.shtml?num=42453 — bad color, again
@@ -49,7 +48,9 @@
         this.stop = false;
     },
     load_into_window: function load_into_window(window, options) {
-        this.process();
+        this.window.document.onreadystatechange = event => {
+            this.process();
+        };
         this.handle_visibilitychange = event => {
             if (this.stop)
                 return;
@@ -139,9 +140,6 @@
                 }
             }
         );
-
-        if (!(this.window.document.hidden) || (this.window.document.readyState !== 'complete'))
-            setTimeout(() => this.process(), this.window.document.readyState !== 'complete' ? 100 : 1000);
     },
     process_CSSStyleSheet: function process_CSSStyleSheet(CSSStyleSheet_v) {
         if (this.stop)
```

**Comment by m-khvoinitsky** [comment]
@benoit-pierre ,

> I think the problem is the way the extension poll each tab's document state with a timeout. I think what should be done instead is to use the readystatechange event to monitor changes.

Not exactly. readystatechange is not what we need. It has following events:  _loading_, _interactive_, _complete_. What we need is to know when the page gets new stylesheet. It may load new stylesheet in any of this states (even in _complete_). It would be great to use some event which fires when new stylesheet gets loaded but there is no such one. So, the only thing I can do is to poll page for new stylesheets. In fact, it's more likely that a page will load new stylesheet before _complete_ state so I can poll it more frequently. After the _complete_ state I still poll page but less frequently and only currently visible page.
The problem with this issue is that nsIDOMWindow for _pending_ tab (restored, not yet loaded) is forever in _interactive_ state. When tab gets completely restored, its nsIDOMWindow gets destroyed and the new one created. So, we just can ignore nsIDOMWindow for _pending_ tabs (8e0f96fcad95242a95330a197dbc04aa42e2853d).

**Comment by m-khvoinitsky** [comment]
@benoit-pierre , BTW, thank you for the report. This issue was the reason for a significant battery drain in my android devices.

**Comment by benoit-pierre** [comment]
I can confirm this fixed the problem, thanks!
