### ISSUE TITLE
Confluence wiki inherits colors when it shouldn't.

### ISSUE THREAD

**Issue by Shickmo** [m-khvoinitsky/dark-background-light-text-extension#153]
Basically when you make confluence wiki pages, confluence is an atlassian product, the colors from the addon are saved when the page is saved. The main problem much the same as issue 152 is that the font colors are so light the text is basically unreadable.

I am using Pop OS, basically Ubuntu 17.1

**Comment by Shickmo** [comment]
Ubuntu 17.10 and the latest version of Firefox. Not sure if this is anything you can fix but worth noting this wasn't an issue before the web extension port.

Thanks for the awesome addon.

**Comment by m-khvoinitsky** [comment]
Which version of confluence do you use?

**Comment by Shickmo** [comment]
Will double check this morning and let you know.

**Comment by m-khvoinitsky** [comment]
I've just checked confluence (5.9.5) — It works *sort of* as expected. Confluence actually preserves the colors which you choose. The problem is that when you choose white color for text on white background, my add-on eliminates unreadable text and you see it good while others don't. I have no idea how it could be fixed. Content editing is sort of special task which requires original colors display. However, you can use "Invert" for such cases — it will preserve hue and the fact whether it's readable on its background or not.

**Comment by m-khvoinitsky** [comment]
I've _mostly_ fixed it in 5d50c008790c3059a011c96d3b7f65518e86aa59. In particular, the add-on won't mess the colors up anymore if you just make a minor edit. However, you still need to be very careful while coloring the page with the add-on enabled: you can't know for sure that the colors you're choosing in the UI with the add-on enabled will also be readable with the add-on disabled. It's better to either use Invert or Disabled for such activity.
