### ISSUE TITLE
Option to not invert images

### ISSUE THREAD

**Issue by spectralsun** [m-khvoinitsky/dark-background-light-text-extension#165]
Delimunate (chrome) has an option to not invert images. I think this is an essential option to add.

**Comment by m-khvoinitsky** [comment]
Not sure what you are talking about. My add-on doesn't invert images.
Provide some screenshots of the problem you encounter.

**Comment by spectralsun** [comment]
There are many, many sites where this happens. Here is one I was on today:

https://www.cmedia.com.tw/
![inverted](https://user-images.githubusercontent.com/2507359/39498670-5d0127ee-4d5e-11e8-9897-bd6df30da38c.jpg)

**Comment by spectralsun** [comment]
Please reopen this issue.

**Comment by m-khvoinitsky** [comment]
Well, first, it's worth saying that you're talking about "Invert" method. Second, "Invert" is actually (sort of) skips images from inverting. There are basically two types (let's ignore everything like list-style-image and similar for now) of images on the web: `<img>` tags and `background-image` CSS property. Ideally, first should be used for everything *meaningful* like pictures, photos and so on, seconds for any background decorations like textures. First is not inverted by "Invert", the seconds is. The problem is that modern websites often abuse both types of images. To make it work great you need sort of artificial intelligence for that task. Also, "Invert" is pure-CSS solution so it's not possible to implement complicated logic there. "Stylesheet Processor" uses some heuristics for the similar task which is not perfect but works good most of the time. The website you provided does exactly this: it uses `background-image` for "meaningful" photos. Skipping `background-image`s from inverting is not possible in pure CSS.

What Deluminate does is uses javascript helper for its CSS with, again, some heuristics. While it's not a bad idea, it requires investing a lot of time into "Invert" what I have no plans to do, unfortunately. I use "Stylesheet Processor" by default and only use other methods if latter behaves really bad.
