### ISSUE TITLE
'.../null' requests in webserver access logs when using Stylesheet Processor

### ISSUE THREAD

**Issue by m-khvoinitsky** [m-khvoinitsky/dark-background-light-text-extension#170]
Probably caused by #96

**Comment by sebastianschauenburg** [comment]
Just wanted to let you know you're not the only one who notices this. I was approached because my browser was hitting the '/null' URL (since it doesn't exist it causes errors on the server side). After checking all my plugins, I found the culprit ;-) (btw, thanks for this addon, it's amazing)
Is there any way to workaround this bug, use another sub-URL for example?

**Comment by aemonge** [comment]
Is this bug related to the fact that when opening files (markdowns) the plugin recognizes the location as `null/C` and therefore it can't black list such files.

I have a markdown displayer already black, and this plugins overkill the blackness, so I want all my local markdown files (or all files) to be black-listed.

![image](https://user-images.githubusercontent.com/1322348/101767661-ceb73600-3ae4-11eb-952d-041089e856f8.png)
