### ISSUE TITLE
Can you explain me in 10 pages why the fuck DO I NEED A LOOP WARNING in your addon ?

### ISSUE THREAD

**Issue by zh0so** [m-khvoinitsky/dark-background-light-text-extension#185]
Example:  https://ibb.co/fFxaHy

That might be usefull for you, but i do not find it usefull when i press disable on your addon, enable greybackgrounds, then the warning pops-up constantly without stopping, how the fuck is that helping anyone ?

The only thing that shuts that warning off is Dnd mode in firefox, that needs to be enabled each startup, imagine doing that 50x a day just for you, if i bother to delete bad_browser_settings.html in the xpi, oh guess what the addon stops working, firefox doesn't approve and no way to change that in ff 54 avoiding quantum for the next 5 years.

All of that because you need to stick a warning that doesnt work on the final version of your addon.

''Developer response

This warning here for a reason. If you use the add-on with high-contrast mode, either follow recommendations in the warning or don't use the add-on at all — with high-contrast mode it does almost nothing.''

No your addon doesnt work everywhere, but greybackgrounds does, you remove your warning and never code a endless waring again. Adblock/Umatrix/ config does not block addons notifications, dnd does not stick I already have to many addons in my bar i dont need other addons for addons to work.

Worst part about problems with addons is that most probably there is no better alternative for specific use on them so swapping this one with a worse one is not an alternative.

**Comment by m-khvoinitsky** [comment]
1. You haven't explained why you just can't follow recommendations in bad_browser_settings.html
   * Is this a problem with compatibility with another add-on?
2. If you don't use my add-on, just disable it completely, in about:addons, not in my add-on's internal settings.
3. If you use pre-57 Firefox, it's better to use [0.5.13](https://addons.mozilla.org/en-US/firefox/addon/dark-background-light-text/versions/0.5.13) — it works everywhere, just like GreyBackgrounds which is legacy add-on (that's because it works everywhere).
4. Using Firefox 54 is insane — if you want to use pre-57 version, use 52 as it is Extended Support Release which still receives security updates. However, it soon will be dropped too. v54 has been dropped long ago.

P. S. I don't have to help you at all. Your shouting and aggressive demand won't help to solve the problem at all or even can prevent the problem from being solved. You should have known this.

**Comment by Grossdm** [comment]
Hey @zh0so,

I get very frustrated at times, add it seems that you were when you opened this issue.

Please try to hold back the vitriol in your first statement or question.

Then, if you are upset by how you were responded to - well you can let loose with the vitriol then. Just understand that people probably won't respond well.

I am reminded of an aphorism that is something like: "You can catch more flies with honey than vinegar."

So keep that in mind when you're on the hunt for flies.
