### ISSUE TITLE
Color scheme changes or background turns white after some 30-60 secs

### ISSUE THREAD

**Issue by gethob1** [m-khvoinitsky/dark-background-light-text-extension#198]
I noticed sometime this month my orange text started randomly changing to blue some 30-60 seconds after the page had loaded.  Now I'm finding my black background keeps turning white after about the same amount of time has elapsed.  It doesn't do it consistently or any particular web page, and I don't believe any of my other plugins are responsible.  Reloading the page does seem to reset it.  Please fix, thank you.

**Comment by m-khvoinitsky** [comment]
Since I don't experience noting similar, try to provide some hints how to reproduce it. 
>  It doesn't do it consistently or any particular web page

However, provide some examples.

> I don't believe any of my other plugins are responsible

It looks like something is wrong with your environment so at least enumerate them.

Also, provide some standard debugging information: add-on preferences, OS, Browser version, etc.
