### ISSUE TITLE
CSS :target for Off-Screen Designs

### ISSUE THREAD

**Issue by pfekelly** [m-khvoinitsky/dark-background-light-text-extension#211]
I researched this method to compose page off screen which might be useful to eliminate annoying interim flash before new page is presented.  Would it be helpful to you?

https://css-tricks.com/css-target-for-off-screen-designs/#comments

**Comment by m-khvoinitsky** [comment]
Well, no, because I can't touch the page a lot. Actually, I have to touch only CSS and even this may sometimes cause some issues. Using this approach I would have to clone whole page DOM to some off-screen element, process it and then reveal? No, this would cause loads of bugs. I'm not even sure it would work with more or less complicated pages.
We have to wait for API improvements.
