### ISSUE TITLE
Color picker broken on mobile

### ISSUE THREAD

**Issue by Geobert** [m-khvoinitsky/dark-background-light-text-extension#221]
On Firefox nightly Android:

![image](https://user-images.githubusercontent.com/72570/66297796-48073780-e8e8-11e9-8291-d9a84bbde448.png)

Been like since I'm using this extension (few months now) :)

**Comment by m-khvoinitsky** [comment]
I completely do not control this color picker. It's controlled by Firefox and Android. You can check if the problem exists on other websites (for example, on [this](https://interactive-examples.mdn.mozilla.net/pages/tabbed/input-color.html) page) and in other apps.

For that reason (and because native Android color picker is poor), you can enter manually any hex RGB color value.
