### ISSUE TITLE
Invert mode causes colour shifts in non-inverted content. Consider add method similar to Invert but without hue-rotate(180deg)

### ISSUE THREAD

**Issue by slowriot** [m-khvoinitsky/dark-background-light-text-extension#23]
Discovered this issue while using the Telegram chat service's web client (web.telegram.org) on Firefox ESR 45.2.0 on linux, 64bit.

Images posted in the web client are not affected by the dark background setting (which is the desirable situation).  However, when "invert" mode is selected, the colours of images are strangely muted.  Below is an example of disabled mode followed by invert mode:
![](https://i.imgur.com/stqk21B.png)
![](https://i.imgur.com/YtHOqSz.png)
Note how the beak of the bird is a much duller yellow colour than the original.

This does not happen in any of the other modes ("stylesheet" or "simple CSS").  You can see the change instantly when switching.

**Comment by m-khvoinitsky** [comment]
Unfortunately, I can't fix this.
Invert mode works the following way: it inverts the whole page, and it inverts pictures which doesn't need to be inverted (twice inverted results in not inverted). So, after two inversions there is some color loss. All this inversions performed by Firefox and I have nothing to do with it.

**Comment by benoit-pierre** [comment]
You could provide a "negate" variant without the `hue-rotate(180deg)`, the colors tones will be different, but this will prevent the loss on double inversion.

**Comment by m-khvoinitsky** [comment]
I've tested it without hue-rotate(180deg) and the color loss in this case is significantly less noticeable (but it is still exists).

> You could provide a "negate" variant without the hue-rotate(180deg), the colors tones will be different, but this will prevent the loss on double inversion.

May be. I'll update issue title.

**Comment by m-khvoinitsky** [comment]
I'd say it's wontfix: while I was able to change filter from built-in invert to transformation matrix which doesn't do luminance correction (see https://github.com/m-khvoinitsky/dark-background-light-text-extension/blob/master/test/test-pages/invert-test/index.html) which reduces color looses but it causes another issue: because of the absence of luminance correction some text on some backgrounds may become less readable.
If you need precise image colors, use Stylesheet Processor.
