### ISSUE TITLE
when opening a page the page itself will do a refresh

### ISSUE THREAD

**Issue by thotivuw** [m-khvoinitsky/dark-background-light-text-extension#233]
when opening a new page the page itself will do a refresh. However when this addon start restyling the page, it refreshes for the second time taking about two seconds before it displays the styled page. It does this very consistently so I don't see a technical problem and I'm not sure if this is what the developer intended but it's ANNOYING to wait for 2 seconds before I start reading or browsing a page.

**Comment by m-khvoinitsky** [comment]
> I'm not sure if this is what the developer intended

Actually, it is. I'll try to explain.

First, you may notice that at the start of loading there is short period of time when page have broken layout or missing styles. The reason is workaround for #96 ([bug 1393022](https://bugzilla.mozilla.org/show_bug.cgi?id=1393022)).

Second, default method of page color modification, Stylesheet Processor, have one drawback: it can't do its work immediately (as opposed to pure-CSS based methods like Simple CSS and Invert). That's why there used to be white flashes at the start of page loading (#131, there was a lot of reasons for them and this is one of them). And the way I worked it around is, roughly speaking, I apply Simple CSS first, then Stylesheet Processor, and when Stylesheet Processor have done it's work (which is not trivial to know for sure, BTW), I remove Simple CSS styles from the page. That's what you probably observe.
