### ISSUE TITLE
Breaks the "Zoom Page WE" addon

### ISSUE THREAD

**Issue by joefiesta** [m-khvoinitsky/dark-background-light-text-extension#237]
I discovered that when DBLT  is running the Zoom Page WE addon becomes inoperative. 

I Run FF 68.0.2 under Windows 7 Professional.

**Comment by m-khvoinitsky** [comment]
I've tried Zoom Page WE with 68.0.2 and it wasn't working even without any other add-on installed. After Firefox updated itself to 68.6.0 (latest ESR version), Zoom Page WE started working even with my add-on. So, try to update your browser first.

**Comment by joefiesta** [comment]
will do.... I'll get back and fix that nasty 1 start review too.

**Comment by joefiesta** [comment]
FF 74 fixed the problem.   geez, I hate updating FF.  Something always
breaks or changes.
 
Anyhow, question:    
1.    What does the "GRAB" box do/mean in the options menu?   I think the
word GRAB  needs some explanation.  I've never seen it used in computer
lingo.
 
2.  F9  ("Toggle enabled for current tab hotkey")  doesn't do anything for
me.  Did I have to GRAB it? 
 
BTW -  I upgraded (to 5!!) my review, but the above questions should realliy
have made it just 4.
 
Joe P.  
    
 
 

  _____

**Comment by joefiesta** [comment]
Mikhail,
 
I think I am beginning to understand the GRAB.  Because I tried it.  I don't
like trying things, just to see what they do, however.   That is totally
unscientific and should not be necessary.    Oh, let's see what happens when
I pull the pin on this hand grenade!!!
 
Problem:   You offer  CTRL+ SHIFT + D as a hotkey for "Toggle Enabled
Hotkey".   After trying the GRAB and following the link that explains
hotkeys (presumably--why must I presume???--that information is just for
hotkeys created by Firefox Addons) I see that I can not override built-in
hotkeys defined, in this case, by Firefox.  CTRL+SHIFT+D is one of those
(Bookmark all Tabs, see here:
https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-task
s-quickly?redirectlocale=en-US
<https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tas
ks-quickly?redirectlocale=en-US&redirectslug=Keyboard+shortcuts>
&redirectslug=Keyboard+shortcuts)
 
It, therefore, seems like not a good idea to offer this specific
combination, CTRL+SHIFT+D,  as a "default".

Pity you can't override Firefox's hotkeys (unless I am misinterpretting
something).   Autohotkey can!  But, that is another story and AHK is totally
different than an addon.
 
Joe P.  
 

  _____

**Comment by m-khvoinitsky** [comment]
> What does the "GRAB" box do/mean in the options menu?   I think the
word GRAB  needs some explanation.  I've never seen it used in computer
lingo.

I've seen this term in computer linquo, may be not in precisely same context but in similar. Yes, It's good to know that it's not obvious so I should probably choose the better one. May be "capture" or even get rid of this word completely buy reworking this page. Add-on UI needs some refresh.

> I see that I can not override built-in
hotkeys defined, in this case, by Firefox.  CTRL+SHIFT+D is one of those
(Bookmark all Tabs, see here:

Indeed. When I've added this feature and chosen this particular key sequence, it wasn't used internally by Firefox. Because I never use this particular hotkey (I do often use "Toggle enabled for current tab hotkey"), I haven't noticed that it was broken. 

By the way, since I've introduced shortcuts feature, Firefox [gathered its own UI for managing add-on shortcuts](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox), so may be I don't need an UI for this at all.

**Comment by joefiesta** [comment]
I was rooting around today and trying to figure out if I can make subdomains
work differently than their main domain.  That would be really nice, but
obviously a little complicated.  One would probably have to manage the
settings via a file (since otherwise it would be difficult to specify how
many levels to go down in the URL).  
 
But, what I think is really needed is MUCH more documentation on your addon.
There is so little it is almost impossible to figure out.   
 
I still can't figure out:   what is the list of "Configured Pages"?    It
certainly appears to be just a list of "Disabled Pages", which makes
"configured pages" inaccurate and confusing.   Secondly, since they all show
as "disabled", maybe each could just have a button to ENABLE it.    And, I
guess the REMOVE button just REMOVES the configuration for that page.   So,
that is essentially an ENABLE button.  (Yes, it removes it from a file, but
users don't see it that way.   And, where is this file?  I would love to be
able to just edit it myself.     I guess that's difficult since it is
probably a cookie, or no?)
 
 
Joe P
 
 

  _____

**Comment by joefiesta** [comment]
Hi,
 
I disabled a domain with DBLT.    But, when I option the options dialogue,
it does not appear under the list of "Configured Pages".   Why?   Do I have
to re-start Firefox or something?
 
Joe P

 
<https://github.com/notifications/beacon/AB2QLYFEPFEAB5JB4LOXBITRIO4HDA5CNFS
M4LFWIP4KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEPP3EVY
.gif>

**Comment by m-khvoinitsky** [comment]
> I was rooting around today and trying to figure out if I can make subdomains
work differently than their main domain.  That would be really nice, but
obviously a little complicated.

This is possible now. Just choose subdomain you need from the menu "Dark Background and Light Text options for:" and set whatever option you need.

> One would probably have to manage the
settings via a file (since otherwise it would be difficult to specify how
many levels to go down in the URL).

It goes indefinitely unless there is an overwrite for more specific subdomain.

> But, what I think is really needed is MUCH more documentation on your addon.
There is so little it is almost impossible to figure out.

Well, I agree. Also, I'm planning to rework the UI in the next version so it would be more easy to use.

> I still can't figure out:   what is the list of "Configured Pages"?    It
certainly appears to be just a list of "Disabled Pages", which makes
"configured pages" inaccurate and confusing.   Secondly, since they all show
as "disabled", maybe each could just have a button to ENABLE it.    And, I
guess the REMOVE button just REMOVES the configuration for that page.   So,
that is essentially an ENABLE button.  (Yes, it removes it from a file, but
users don't see it that way.

You can not only disable for page, but also choose different method for it (Simple CSS, Invert, etc.), so everything would be displayed on this list. Button "Remove" means that overwrite for this page will be removed and the default preferences will be used.

>  And, where is this file?  I would love to be
able to just edit it myself.     I guess that's difficult since it is
probably a cookie, or no?)

It uses [Storage WebExtensions API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage) which used to save this preferences in json file in Firefox profile folder but now it uses IndexedDB or something, I'm not sure. In general, underlying storage is hidden from add-on developer.

> I disabled a domain with DBLT.    But, when I option the options dialogue,
it does not appear under the list of "Configured Pages".   Why?   Do I have
to re-start Firefox or something?

No, this list should be updated in real time. If there is a glitch or something, you can try to reopen preferences page. Or, if you're configuring domain in private window, this preferences will live until you close last private tab and will never be displayed in `Configured Pages`, so may be this is the case.

**Comment by joefiesta** [comment]
Hi,
 
When I enable DBLT on certain pages that contain images, the images are not
visible.
 
For, example, try this page:  https://www.apple.com/iphone-11/specs/
 
All my Ebay pages work fine.  This is Apple page.   I HATE APPLE and they
are probably doing something different.
 
Joe Petree
