### ISSUE TITLE
Doesn't reset colors on disable or remove

### ISSUE THREAD

**Issue by CTimmerman** [m-khvoinitsky/dark-background-light-text-extension#239]
Fortunately about:config has reset buttons for custom color values, but it would be nice to not have to do that.

**Comment by m-khvoinitsky** [comment]
1. Since [runtime.onSuspend](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onSuspend) is [not supported in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1606215), I can't implement proper unloading of add-on from pages. You have to reload them manually.
2. I do not overwrite any preferences regarding colors. All add-on color preferences are separate from Firefox ones.
