### ISSUE TITLE
Remove comments from injected code

### ISSUE THREAD

**Issue by Gitoffthelawn** [m-khvoinitsky/dark-background-light-text-extension#256]
The CSS being injected includes comments.

I recommend using a pre-processor during the build process to remove the comments to optimize the extension's speed and memory use.

**Comment by m-khvoinitsky** [comment]
I'm not sure that you'll save noticeable amount of memory on this. While this is good idea in general, I would not do it unless I'll have to do some style-templating refactoring because it's a classic case of premature optimization. There is at least one thing that should be considered: all add-on CSS files aren't really CSS — they are templates for some dead simple homegrown 30 SLoC built-in templating engine. So, most likely (I haven't actually checked) common CSS minifiers won't be able to handle it out of the box.

**Comment by Gitoffthelawn** [comment]
When I use Firefox's devtools to view the injected CSS, the comments are being injected too.  So, the extension is definitely injecting the comments into each page in each tab.

**Comment by m-khvoinitsky** [comment]
So, I've done some stylesheet-related refactoring and now there are no more comments in rendered code. Also, the rendering itself now is at least 10 — 20 times faster. Unfortunately, it unlikely will be noticed by users because the rendering only happens at Firefox start and preferences change, but still.
