### ISSUE TITLE
Remove unneeded bulk from code injections

### ISSUE THREAD

**Issue by Gitoffthelawn** [m-khvoinitsky/dark-background-light-text-extension#257]
I made multiple pull requests to remove much of the excess injected code.

There is still some code that can possibly be removed, but I wanted to confirm before editing/pulling.

For example:

   1. XUL references in base.css
   2. treechildren references in base.css
   3. Site-specific styles that may no longer be needed in base.css
   4. Bittorrent sync fix (that gets applied to every site) in stylesheet-processor.css
   5. Comments - see #256

**Comment by m-khvoinitsky** [comment]
In general, it's a good idea to remove a bunch of obsolete stuff. However, I'd ask you to merge everything in a single Pull Request — there is no point of splitting this changes depending on files changed because overall it's a single and related change — and it complicates the review.
[3] Yep, I've checked few of them — some does not exists anymore, some has been significantly redesigned so the workaround may not be working or needed anymore.
[4] The reason why Bittorrent sync fix was applied everywhere is because it's self-hosted and you don't know its real domain. However, again, this fix was added ages ago and very likely not needed anymore (there is even no bittorrent sync anymore — it has been renamed), so, I think it can be removed too.

**Comment by Gitoffthelawn** [comment]
Sounds good.  What are your thoughts about [1] and [2]?

**Comment by m-khvoinitsky** [comment]
Yep, removing everything XUL-related (including treechildren) is fine.

**Comment by Gitoffthelawn** [comment]
@m-khvoinitsky Thanks.

**Comment by m-khvoinitsky** [comment]
During the refactoring mentioned in https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/256#issuecomment-753687730 I've done most of your recommendations. I'll close PRs.
