### ISSUE TITLE
0.7.3 ignores styling on AMO

### ISSUE THREAD

**Issue by atomGit** [m-khvoinitsky/dark-background-light-text-extension#273]
with the 0.7.3 version, the ext. no longer works on AMO - this is with extensions.webextensions.restrictedDomains = ""

**Comment by m-khvoinitsky** [comment]
I don't think that this is related to 0.7.3 update (and to be sure I've tested and it doesn't work with 0.7.2 and empty `extensions.webextensions.restrictedDomains` too).
I suppose that Firefox since some recent version treats AMO differently but I haven't checked.
[bug 1411641](https://bugzilla.mozilla.org/show_bug.cgi?id=1411641) may also be related but doesn't looks like on the first sight.
So, I guess, there is nothing I can do here.

**Comment by atomGit** [comment]
0.7.2 worked for me on AMO with FF v78 - i'm not positive it worked with 79, but i check AMO daily and the styling was lost as soon as i updated to 0.7.3

**Comment by atomGit** [comment]
looking at this again, it appears it's a CSP issue at AMO

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).`

**Comment by atomGit** [comment]
this can be overridden with a header editor extension

header name: content-security-policy
value: style-src
type: response
action: delete
