### ISSUE TITLE
Latest seamonkey update (2.53.7) breaks support for dark-background-light-text extension

### ISSUE THREAD

**Issue by jones23** [m-khvoinitsky/dark-background-light-text-extension#291]
It works with with last version 2.53.6.
I know that the sea monkey version isn't being actively maintained, but it has been working fine for the last 4+ years. maybe it's an easy fix. i would really appreciate it i you could take a look. thanks
thomas

**Comment by m-khvoinitsky** [comment]
Looked into it. Unfortunately, it's not an easy fix — it looks like all Add-on SDK extensions have been broken. The reason seems to be the removal of legacy generators (yield in non-asterisk functions) which are still used in Add-on SDK code. I've contacted SeaMonkey developers, will post here when there will be something.

**Comment by m-khvoinitsky** [comment]
[SeaMonkey bug — https://bugzilla.mozilla.org/show_bug.cgi?id=1702903](https://bugzilla.mozilla.org/show_bug.cgi?id=1702903).

**Comment by jones23** [comment]
working again now with version 2.53.7.1 ! thank you very much for raising the issue !!
