### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by kstev99** [m-khvoinitsky/dark-background-light-text-extension#292]
I noticed that the last Beta release was in FEB 2020.  Love this add-on, use it every day, but I am wondering if the project is still active?

**Comment by m-khvoinitsky** [comment]
It is.
Usually I work on it in "batches" — so it may look inactive for months, but if there is some critical regression (usually because of changes in Firefox or some major website), I usually fix the problem ASAP, or if I managed to find a time to work on some big feature — I do it.
I'd love to spend more time on the project, I'm doing my best but I think there is a room for improvements.

My nearest plans are to make some redesign with (finally!) translations which would require some community involvement. I've created some chat ([Gitter](https://gitter.im/dark-background-light-text-extension/community), [Matrix](https://matrix.to/#/#dark-background-light-text-extension_community:gitter.im)) for community (which I haven't advertised anywhere — no surprise that it's empty). If you want to help somehow — you're welcome, however, be warned: my experience in maintaining community project is close to zero, whatever it will lead to.
