### ISSUE TITLE
Invert mode is faulty on long pages

### ISSUE THREAD

**Issue by slowriot** [m-khvoinitsky/dark-background-light-text-extension#40]
Recent versions of firefox now darken the entire page aside from matching search terms when you use ctrl-f to find text in the page.

If the page is currently in "invert" mode with this extension, the result is a completely black page, which stays black even after you cancel out of the find dialogue.

Steps to reproduce:
- Get firefox nightly
- Navigate to a text-heavy page such as https://github.com/gcc-mirror/gcc/blob/master/gcc/doc/invoke.texi
- Set mode to invert
- Press ctrl-f and type something that appears midway down the page or lower
- Page goes black, and stays black even after you press escape to get out of the search dialogue.

I'd include a screenshot but there's really not much point adding a screenshot of a completely black page.

**Comment by m-khvoinitsky** [comment]
Seems like another Firefox bug related to filters.
However, this bug is not related neither to new search behavior nor new firefox version. It reproduces with Firefox 35 (when not SVG filters was introduced), not sure about older versions and SVG filters but seems like it reproduces too (I've tested Firefox 24, got slightly different behavior but similar).

**Comment by m-khvoinitsky** [comment]
In newer version Invert mode has been rewritten to use `backdrop-filter` (see #126 for details) which likely should fix this problem too.
