### ISSUE TITLE
Option to inherit settings from parent domains

### ISSUE THREAD

**Issue by AndrewFerr** [m-khvoinitsky/dark-background-light-text-extension#49]
It's possible to configure DB&LT settings for specific subdomains, but it there isn't a way to use the same settings for sites that share a common parent domain.

In other words, if a site is organized into subdomains (*something*.stackexchange.com, *language*.wikipedia.org), there currently isn't a way for DB&LT to automatically give each subdomain site the same settings as its "parent" site. The only way to give each site the same DB&LT setting is to manually apply it for each one.

One way to do this would be to let "Default" mode inherit settings from parent domains, similar to how it inherits settings from parent directories.

Maybe related to #19 .

**Comment by m-khvoinitsky** [comment]
This _should be_ possible right now.
You can open, for example, en.wikipedia.org, open add-on's popup, in a drop-down menu choose "wikipedia.org" instead of "en.wikipedia.org" and choose, for example, "Disabled". Now, add-on should be disabled across all wikipedia.org subdomains.
But, as I just found out, it's broken. I will fix it very soon.
Thank you for pointing it out.

**Comment by m-khvoinitsky** [comment]
A fixed version will be released in a day or two.

**Comment by AndrewFerr** [comment]
Thanks for the fix!
