### ISSUE TITLE
Dark boxes after disabling addon

### ISSUE THREAD

**Issue by 211217613** [m-khvoinitsky/dark-background-light-text-extension#61]
I was having similar issues with some dialog boxes and disabled then uninstalled the addon. I still have dark boxes. any way to reset this?
![image](https://cloud.githubusercontent.com/assets/7006850/21781992/a3663c76-d666-11e6-8aa6-e617732cc525.png)

**Comment by m-khvoinitsky** [comment]
It's not related to the add-on at all. The website on your screenshot do not explicitly set background color of it's controls and Firefox chooses to follow your desktop settings which seems to be dark. It's not the best kind of behavior because the majority of website developers assume default colors to be light background and dark text. So, there are some bugreports about it (like this [https://bugzilla.mozilla.org/show_bug.cgi?id=519763](https://bugzilla.mozilla.org/show_bug.cgi?id=519763))
You can find a workaround here: [https://wiki.archlinux.org/index.php/Firefox#Unreadable_input_fields_with_dark_GTK.2B_themes](https://wiki.archlinux.org/index.php/Firefox#Unreadable_input_fields_with_dark_GTK.2B_themes)
