### ISSUE TITLE
Disable this addon for devtools also when the addon is disabled on page.

### ISSUE THREAD

**Issue by vijaykm2** [m-khvoinitsky/dark-background-light-text-extension#64]
I have been using this addon for many months and it like it very much. Only issue I found is:
 When the addon is disabled on page, it is not completely disabled in devtools also. For example in the attached screenshot, it is not disabled in devtools menubar and also in react tab. Devtools menubar has a light theme but it is dark.

I am using Nightly in OSX.
<img width="1440" alt="screen shot 2017-02-08 at 9 51 48 pm" src="https://cloud.githubusercontent.com/assets/6619551/22768576/b0650e80-ee48-11e6-963e-88ade3f36ebb.png">

**Comment by m-khvoinitsky** [comment]
Devtools is not a part of a page. It's a separate "page". It should be possible to configure it too, there is an issue for that - #10. However, in particular with devtools it work a bit different: devtools have a few built-in themes: dark, light and FireBug-like. My add-on forces enabling of dark variant. That's actually should be configurabe.

**Comment by dhrv** [comment]
> My add-on forces enabling of dark variant. That's actually should be configurabe.
Yes, please make this configurable and don't force the dark theme. Thank you!

**Comment by m-khvoinitsky** [comment]
Well, I've misunderstood you a bit.
About the react tab - it's not built in firefox but a separate extension so it doesn't use firefox devtools theme — #10 is the case. Until then you can open [resource://react-devtools/data/](resource://react-devtools/data/) in a regular tab and disable the add-on for this url.
About the devtools tab/menu bar — fixed in 2eea9deffb2439335fa3f6140392cf73682edc26
bq. My add-on forces enabling of dark variant. That's actually should be configurabe.
I'm going to remove this feature because it will be impossible to implement it with WebExtensions. Anyway, most users use default theme which is not depends on devtools theme while advanced users can choose appropriate devtools theme or Firefox' "Compact Dark"
