### ISSUE TITLE
Stopped working on Youtube.

### ISSUE THREAD

**Issue by Speaker1264** [m-khvoinitsky/dark-background-light-text-extension#67]
The stylesheet processor used to work very well on youtube, but something must have changed recently, because now everything is blindingly white.  The simple CSS and invert options still work, but with some downsides unfortunately, like making the video's duration impossible to see, or inverting the colors of the video when playing in full screen mode or theater mode.  I hope you can make the stylesheet processor work again for youtube, thanks.

**Comment by m-khvoinitsky** [comment]
May be google updated something on youtube. Google usually does this gradually and it seems that this change haven't arrived for me. So, it works for me. I've tried several ways to enable "new design" or whatever but I haven't managed to reproduce it. I will keep trying.

**Comment by Speaker1264** [comment]
Okay I figured it out there are some additional options youtube added.  They added their own dark mode.  If you enable it youtube looks like a dark grey color now, with it disabled it goes all white.  To get the extension to work again you have to use the Restore Classic Youtube option.  Now, if you are using the old classic youtube design, the only way to revert back to the new youtube design is to clear your browser's cookies.

Here's an image to help show what I'm talking about.  I hope it helps.
[img]http://i.imgur.com/SuwqIZi.png[/img]

**Comment by m-khvoinitsky** [comment]
I've reproduced it. Found some cookies trick to enable new design on youtube.

The problem is that they started to use CSS variables while the add-on isn't properly handles them. I've created #68 for tracking CSS var support implementation but because it's not trivial and will take some time I will have to make some workaround for youtube as soon as possible.

As you've aleady mentioned, users can use one of two workarounds:
* enable youtube's dark mode
* restore youtube classic design
