### ISSUE TITLE
Very slow to darken previously loaded pages

### ISSUE THREAD

**Issue by Dudes1** [m-khvoinitsky/dark-background-light-text-extension#86]
First off, thanks for all you do, love this add-on!

Aa 0.5.10 & Firefox 54.0.1

For example- I've this post typed out and ready to submit, I tap home on my navbar, tap recents, swipe away Firefox, and then launch it again from the app drawer.  It displayed a white page for about seven seconds before going dark with this post just as I left it. Seven seconds is a long time. Maybe it's my phone and provider, I don't know, just reporting my experience. 

Nexus 4, Android 7.1.2, T-Mobile.

**Comment by m-khvoinitsky** [comment]
Unfortunately, I can't fix this.
The problem is that Firefox doesn't wait until all add-ons are loaded before loading any page and showing anything (otherwise it would significantly slow it down). So, this seven seconds is a time when my add-on isn't loaded yet. The long time itself is probably related to Firefox issues — I'm experiencing this even on rather powerful devices.
