### ISSUE TITLE
Pale Moon support

### ISSUE THREAD

**Issue by SkyWheel** [m-khvoinitsky/dark-background-light-text-extension#91]
Hi Mikhail,
Is it possible to support Pale Moon?
Thank you.

**Comment by m-khvoinitsky** [comment]
Well, in the long term, I don't know.
Palemoon developers claim that they aren't going to support WebExtensions, so no way here.
Albeit they dropped Jetpack support completely in 27, they returned some stripped down version in 27.1 which they call PMKit. Due to it's stripped down, it doesn't have some essential components to support my add-on, in particular it's `sdk/remote/*` which is reasoned as they have no plans to support e10s so there are no need to support `sdk/remote/*` however they do support, for example, parentprocessmessagemanager which `sdk/remote/*` actually wraps. So, it doesn't look consistent.

Moreover, my main goal is Firefox which means that I'll migrate to WebExtensions. However, I still can support older jetpack version (as low priority and only if it would be easy to backport some feature\fix) for SeaMonkey (which doesn't work now but I'm going to fix it in one of the nearest releases, see #85). So, if Palemoon developers decide to maintain more close compatibility to Firefox' jetpack, I would happy to support it upstream.

There is a fork of my add-on: [Advanced Night Mode](https://addons.palemoon.org/addon/advanced-night-mode/) which maintains compatibility with Palemoon, it is based on my add-on's older code which uses parentprocessmessagemanager and, consequently, has some nasty bugs (like this — #36) which however you won't notice most of the time.

**Comment by SkyWheel** [comment]
Wow!
Bol'shoe spasibo for the fork link!
It suits my basic needs.
