### ISSUE TITLE
White page before load

### ISSUE THREAD

**Issue by slk500** [m-khvoinitsky/dark-background-light-text-extension#98]
Extension have worked great, but after system updates it changed behavior. When the page have white background like google.com on loading time I see white background for a second. It's really annoying. I have Firefox 56.0, also tried with 55.0 version. Even remove all other extension. But still the same.

**Comment by m-khvoinitsky** [comment]
Which version do you have? 0.5.14? If yes, the reason is probably the delay of passing the preferences from WebExtensions part to jetpack part. I see no reason for trying to improve the situation because in less than three weeks there will be released new pure WebExtension version which... has the same issue but much more severely. Yes, unfortunately, but there are no more required API to improve the situation as I was doing this before. I have some thoughts on how to improve it but it will require some collaboration and improvements from Firefox side which means that it doesn't depends on me. However, I have a strong desire to work on it because it annoys me significantly too.
But, that's a topic of other issues, so, closing this for now.

**Comment by m-khvoinitsky** [comment]
See https://github.com/m-khvoinitsky/dark-background-light-text-extension/issues/71#issuecomment-340042356 for details.
